# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
dev.kikugie.stonecutter.hard_mode=true

# Mod Properties
mod_version=2.1.4
maven_group=dev.xirreal.viewfinder
archives_base_name=viewfinder

loom_version=1.17.21
