name: release

on:
   push:
      tags:
         - "v*"

permissions:
   contents: write

jobs:
   release:
      runs-on: ubuntu-22.04
      steps:
         - name: checkout repository
           uses: actions/checkout@v4

         - name: validate gradle wrapper
           uses: gradle/wrapper-validation-action@v2

         - name: setup jdk 25
           uses: actions/setup-java@v4
           with:
              java-version: 25
              distribution: "microsoft"

         - name: make gradle wrapper executable
           run: chmod +x ./gradlew

         - name: build
           run: ./gradlew build

         - name: publish Minecraft 26.1
           uses: Kir-Antipov/mc-publish@v3.3
           with:
              modrinth-id: ${{ vars.MODRINTH_PROJECT_ID }}
              modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

              github-tag: ${{ github.ref_name }}
              github-generate-changelog: true
              github-token: ${{ secrets.GITHUB_TOKEN }}

              files: versions/26.1/build/libs/!(*-sources).jar
              github-files: versions/*/build/libs/!(*-sources).jar
              name: Viewfinder ${{ github.ref_name }} for Minecraft 26.1
              version: ${{ github.ref_name }}+26.1
              loaders: fabric
              game-versions: 26.1
              version-type: release

         - name: publish Minecraft 26.2
           uses: Kir-Antipov/mc-publish@v3.3
           with:
              modrinth-id: ${{ vars.MODRINTH_PROJECT_ID }}
              modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

              files: versions/26.2/build/libs/!(*-sources).jar
              name: Viewfinder ${{ github.ref_name }} for Minecraft 26.2
              version: ${{ github.ref_name }}+26.2
              loaders: fabric
              game-versions: 26.2
              version-type: release

         - name: publish Minecraft 26.3
           uses: Kir-Antipov/mc-publish@v3.3
           with:
              modrinth-id: ${{ vars.MODRINTH_PROJECT_ID }}
              modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

              files: versions/26.3/build/libs/!(*-sources).jar
              name: Viewfinder ${{ github.ref_name }} for Minecraft 26.3
              version: ${{ github.ref_name }}+26.3
              loaders: fabric
              game-versions: 26.3
              version-type: release
