name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: Viewfinder ${{ github.event.release.tag_name }}
          version: ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}

          loaders: fabric
          game-versions: 26.1
          java: 21
